pub(super) const EXPECTED_CONTROLS: &[(&str, &str)] = &[
    ("button:South", "South"),
    ("button:East", "East"),
    ("button:North", "North"),
    ("button:West", "West"),
    ("button:LeftTrigger", "Left bumper"),
    ("button:LeftTrigger2", "Left trigger"),
    ("button:RightTrigger", "Right bumper"),
    ("button:RightTrigger2", "Right trigger"),
    ("button:Select", "Select"),
    ("button:Start", "Start"),
    ("button:Mode", "Mode"),
    ("button:LeftThumb", "Left stick click"),
    ("button:RightThumb", "Right stick click"),
    ("button:DPadUp", "D-pad up"),
    ("button:DPadDown", "D-pad down"),
    ("button:DPadLeft", "D-pad left"),
    ("button:DPadRight", "D-pad right"),
    ("axis:LeftStickX", "Left stick horizontal"),
    ("axis:LeftStickY", "Left stick vertical"),
    ("axis:RightStickX", "Right stick horizontal"),
    ("axis:RightStickY", "Right stick vertical"),
];
